export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const GET_PRODUCT_ID_START = "GET_PRODUCT_ID_START";
export const GET_PRODUCT_ID_SUCCESS = "GET_PRODUCT_ID_SUCCESS";
export const GET_PRODUCT_ID_FAIL = "GET_PRODUCT_ID_FAIL";

export const SET_PRODUCT_ID = "SET_PRODUCT_ID";

export const SET_SELECTED_DAY = "SET_SELECTED_DAY";
export const SET_SELECTED_TIME = "SET_SELECTED_TIME";
export const SET_SELECTED_COUNT = "SET_SELECTED_COUNT";
