export const ADD_PRODUCT_TO_FAVS_START = "ADD_PRODUCT_TO_FAVS_START";
export const ADD_PRODUCT_TO_FAVS_SUCCESS = "ADD_PRODUCT_TO_FAVS_SUCCESS";
export const ADD_PRODUCT_TO_FAVS_FAIL = "ADD_PRODUCT_TO_FAVS_FAIL ";

export const DELETE_PRODUCT_FROM_FAVS_START = "DELETE_PRODUCT_FROM_FAVS_START";
export const DELETE_PRODUCT_FROM_FAVS_SUCCESS =
	"DELETE_PRODUCT_FROM_FAVS_SUCCESS";
export const DELETE_PRODUCT_FROM_FAVS_FAIL = "DELETE_PRODUCT_FROM_FAVS_FAIL ";

export const SET_PRODUCT_ID = "SET_PRODUCT_ID";

export const GET_FAVS_START = "GET_FAVS_START";
export const GET_FAVS_SUCCESS = "GET_FAVS_SUCCESS";
export const GET_FAVS_FAIL = "GET_FAVS_FAIL";
