export const ADD_PRODUCT_TO_FAVS_START = "ADD_PRODUCT_TO_FAVS_START";
export const ADD_PRODUCT_TO_FAVS_SUCCESS = "ADD_PRODUCT_TO_FAVS_SUCCESS";
export const ADD_PRODUCT_TO_FAVS_FAIL = "ADD_PRODUCT_TO_FAVS_FAIL ";

export const SET_PRODUCT_ID = "SET_PRODUCT_ID";
